version: "3.8"

services:
  dallebash-image-generator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      NODE_ENV: development
    volumes:
      - .:/usr/src/app
